"""
Generate realistic sample data.

v2 additions:
  * The scheme settlement file is now ALSO written as ISO 20022 camt.053 XML
    (data/scheme_settlement.camt053.xml), structurally modelled on the public
    Danske Bank example (data/samples/camt053_danske_example.xml), so the
    pipeline exercises a real bank statement format end-to-end.
  * A NEXT settlement window file (data/scheme_settlement_next_window.csv):
    half of the "missing in scheme file" transactions deliberately land
    there. The triage agent's check_next_window tool can then prove they are
    cutoff/timing differences — exactly the check a human analyst performs.
  * A scheme fee schedule (data/fee_schedule.json) matching the injected
    amount-mismatch deltas, so the agent can verify fee-netting mismatches
    against a source of truth instead of guessing.

Injected exception types (what reconciliation teams actually deal with):
  - amount mismatches (fee netted at settlement)
  - missing in ledger (scheme settled, we never booked it)
  - missing in scheme file (we booked it, scheme never settled — half of
    these are timing differences that appear in the next window)
  - duplicate settlement entries
  - reference truncation / format drift
"""

import csv
import json
import random
import uuid
from datetime import datetime, timedelta
from pathlib import Path
from xml.sax.saxutils import escape

random.seed(42)

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
N_CLEAN = 180          # transactions that reconcile perfectly
N_EXCEPTIONS = 20      # transactions with injected issues

SCHEME_FEES = [1.5, 2.0, 4.5]   # flat fees netted at settlement

MERCHANTS = [
    "KIRANA-STORE-4411", "SWIFTCART-IN", "METRO-FUEL-22", "CLOUDKITCHEN-88",
    "PHARMA-PLUS-BLR", "TRAVELDESK-DEL", "EDUTECH-PRIME", "GROCER-DAILY-77",
]


def _txn(base_time: datetime):
    ref = f"STL{uuid.uuid4().hex[:12].upper()}"
    amount = round(random.uniform(50, 95000), 2)
    ts = base_time + timedelta(seconds=random.randint(0, 86_000))
    return {
        "settlement_ref": ref,
        "amount": amount,
        "currency": "INR",
        "counterparty": random.choice(MERCHANTS),
        "value_date": ts.strftime("%Y-%m-%d"),
        "timestamp": ts.strftime("%Y-%m-%dT%H:%M:%S"),
        "direction": random.choice(["CREDIT", "DEBIT"]),
    }


# ------------------------------------------------------- camt.053 writer ---

CAMT_ENTRY = """			<Ntry>
				<NtryRef>{ntry_ref}</NtryRef>
				<Amt Ccy="{ccy}">{amount:.2f}</Amt>
				<CdtDbtInd>{cdtdbt}</CdtDbtInd>
				<Sts>BOOK</Sts>
				<BookgDt><Dt>{value_date}</Dt></BookgDt>
				<ValDt><Dt>{value_date}</Dt></ValDt>
				<AcctSvcrRef>{ref}</AcctSvcrRef>
				<NtryDtls>
					<TxDtls>
						<Refs>
							<EndToEndId>{ref}</EndToEndId>
						</Refs>
						<AmtDtls>
							<TxAmt><Amt Ccy="{ccy}">{amount:.2f}</Amt></TxAmt>
						</AmtDtls>
						<RltdPties>
							<Dbtr><Nm>{counterparty}</Nm></Dbtr>
						</RltdPties>
						<RmtInf><Ustrd>Settlement {ref}</Ustrd></RmtInf>
					</TxDtls>
				</NtryDtls>
			</Ntry>"""


def write_camt053(rows: list[dict], path: Path, stmt_date: str):
    """Write scheme rows as a camt.053-shaped XML statement."""
    entries = "\n".join(
        CAMT_ENTRY.format(
            ntry_ref=i + 1,
            ccy=r["currency"],
            amount=float(r["amount"]),
            cdtdbt="CRDT" if r["direction"] == "CREDIT" else "DBIT",
            value_date=r["value_date"],
            ref=escape(r["settlement_ref"]),
            counterparty=escape(r["counterparty"]),
        )
        for i, r in enumerate(rows)
    )
    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.053.001.02">
	<!-- Synthetic settlement statement generated by Settlement Sentinel -->
	<!-- Structure modelled on the public Danske Bank camt.053 example:
	     https://danskeci.com/-/media/pdf/danskeci-com/iso-20022-xml/camt053_dk_example.xml -->
	<BkToCstmrStmt>
		<GrpHdr>
			<MsgId>SENTINEL{stmt_date.replace('-', '')}001</MsgId>
			<CreDtTm>{stmt_date}T23:59:00</CreDtTm>
		</GrpHdr>
		<Stmt>
			<Id>SENTINEL{stmt_date.replace('-', '')}001</Id>
			<CreDtTm>{stmt_date}T23:59:00</CreDtTm>
			<Acct>
				<Id><IBAN>HU42117730161111101800000000</IBAN></Id>
				<Ccy>INR</Ccy>
				<Nm>Scheme Settlement Account</Nm>
			</Acct>
{entries}
		</Stmt>
	</BkToCstmrStmt>
</Document>
"""
    path.write_text(xml)
    print(f"wrote {len(rows):4d} entries -> {path}")


# ------------------------------------------------------------- generator ---

def generate():
    DATA_DIR.mkdir(exist_ok=True)
    base = datetime(2026, 7, 6)
    next_window_date = (base + timedelta(days=1)).strftime("%Y-%m-%d")

    scheme_rows, ledger_rows, next_window_rows = [], [], []

    # --- clean, matching transactions -------------------------------------
    for _ in range(N_CLEAN):
        t = _txn(base)
        scheme_rows.append(dict(t))
        ledger_rows.append(dict(t))

    # --- injected exceptions ----------------------------------------------
    missing_in_scheme_count = 0
    for i in range(N_EXCEPTIONS):
        t = _txn(base)
        kind = i % 5

        if kind == 0:  # amount mismatch: scheme nets a processing fee
            s = dict(t)
            l = dict(t)
            l["amount"] = round(t["amount"] - random.choice(SCHEME_FEES), 2)
            scheme_rows.append(s)
            ledger_rows.append(l)

        elif kind == 1:  # settled by scheme, never booked internally
            scheme_rows.append(dict(t))

        elif kind == 2:  # booked internally, missing from scheme file
            ledger_rows.append(dict(t))
            # half of these are timing differences: they settle next window
            missing_in_scheme_count += 1
            if missing_in_scheme_count % 2 == 1:
                nxt = dict(t)
                nxt["value_date"] = next_window_date
                next_window_rows.append(nxt)

        elif kind == 3:  # duplicate settlement entry in scheme file
            scheme_rows.append(dict(t))
            scheme_rows.append(dict(t))
            ledger_rows.append(dict(t))

        else:  # reference truncated by legacy formatting in ledger
            s = dict(t)
            l = dict(t)
            l["settlement_ref"] = t["settlement_ref"][:10]
            scheme_rows.append(s)
            ledger_rows.append(l)

    random.shuffle(scheme_rows)
    random.shuffle(ledger_rows)

    # CSV outputs (scheme CSV kept for --scheme-format csv compatibility)
    for name, rows in [("scheme_settlement.csv", scheme_rows),
                       ("internal_ledger.csv", ledger_rows),
                       ("scheme_settlement_next_window.csv", next_window_rows)]:
        path = DATA_DIR / name
        with open(path, "w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=list(scheme_rows[0].keys()))
            writer.writeheader()
            writer.writerows(rows)
        print(f"wrote {len(rows):4d} rows -> {path}")

    # camt.053 output — same scheme data, real bank-statement format
    write_camt053(scheme_rows, DATA_DIR / "scheme_settlement.camt053.xml",
                  base.strftime("%Y-%m-%d"))

    # fee schedule — source of truth for the agent's fee check
    fee_path = DATA_DIR / "fee_schedule.json"
    fee_path.write_text(json.dumps({
        "scheme": "DEMO-INSTANT",
        "currency": "INR",
        "fees": [
            {"type": "processing_fee_flat", "amount": f,
             "netted_at_settlement": True}
            for f in SCHEME_FEES
        ],
    }, indent=2))
    print(f"wrote fee schedule -> {fee_path}")


if __name__ == "__main__":
    generate()
